#!/bin/bash
set -e

# Set Zsh as default shell for new users
if command -v zsh >/dev/null 2>&1; then
    chsh -s /usr/bin/zsh
fi

# Apply RudyRainOS default wallpaper
if [ -f /usr/share/rudyraindesktop/wallpapers/default.jpg ]; then
    gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/rudyraindesktop/wallpapers/default.jpg"
    gsettings set org.gnome.desktop.background picture-uri-dark "file:///usr/share/rudyraindesktop/wallpapers/default.jpg"
fi

# Apply RudyRainOS GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "RudyRainGTK"

# Apply RudyRainOS icon theme
gsettings set org.gnome.desktop.interface icon-theme "RudyRainIcons"

# Apply RudyRainOS cursor theme
gsettings set org.gnome.desktop.interface cursor-theme "RudyRainCursor"

# Apply RudyRainOS Shell theme
gsettings set org.gnome.shell.extensions.user-theme name "RudyRainShell"

# Apply RudyRainOS Terminal Theme
if [ -f /usr/share/rudyraindesktop/terminal-profiles/RudyRainOS.json ]; then
    dconf load /org/gnome/terminal/legacy/profiles:/ < /usr/share/rudyraindesktop/terminal-profiles/RudyRainOS.json
fi

exit 0
